# Generated by Django 3.2.5 on 2021-08-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpage',
            name='content',
        ),
        migrations.AddField(
            model_name='pagesection',
            name='alt_tag_image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
