# Generated by Django 3.2.5 on 2021-08-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='background',
            field=models.ImageField(upload_to='component/contact/background/'),
        ),
    ]
