# Generated by Django 3.2.5 on 2021-08-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0007_alter_contact_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siterequirement',
            name='location_iframe',
            field=models.URLField(max_length=350),
        ),
    ]
