# Generated by Django 3.2.5 on 2021-07-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='post',
            name='alt_tag_banner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
