# Generated by Django 3.2.5 on 2021-08-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='alt_tag_banner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
