# Generated by Django 3.2.5 on 2021-07-29 21:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=60, unique=True)),
                ('icon', models.CharField(help_text="Please visit <a target='_blank' href='https://linearicons.com/free'>Linear Icons</a>", max_length=30)),
                ('lead_h1', models.CharField(blank=True, max_length=100, null=True)),
                ('service_tagline', models.CharField(blank=True, max_length=100, null=True)),
                ('banner', models.ImageField(upload_to='services/banners/')),
                ('content', ckeditor.fields.RichTextField()),
                ('seo_tag', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.seotag')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(help_text="Please visit <a target='_blank' href='https://linearicons.com/free'>Linear Icons</a>", max_length=30)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='services/processes/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
