# Generated by Django 3.2.5 on 2021-07-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprocess',
            options={'verbose_name_plural': 'Service processes'},
        ),
        migrations.AddField(
            model_name='service',
            name='common_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
