# Generated by Django 3.2.5 on 2021-08-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210730_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprocess',
            name='alt_tag_image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
