# Generated by Django 3.2.5 on 2021-07-29 21:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=100)),
                ('thumbnail', models.ImageField(upload_to='project/thumbnails/')),
                ('description', ckeditor.fields.RichTextField()),
                ('featured', models.BooleanField(default=False)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('featured_background', models.ImageField(blank=True, null=True, upload_to='cases/featured/background/')),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('thumbnail', models.ImageField(upload_to='project/thumbnails/')),
                ('description', ckeditor.fields.RichTextField()),
                ('website_link', models.URLField()),
                ('featured', models.BooleanField(default=False)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project/images/')),
                ('alt_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='project/cases/images')),
                ('alt_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.casestudy')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudyScoreBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointer', models.CharField(max_length=35)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.casestudy')),
            ],
        ),
        migrations.AddField(
            model_name='casestudy',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='seo_tag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.seotag'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service'),
        ),
    ]
