# Generated by Django 3.2.5 on 2021-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210803_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='tagline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
